stages:
  - build

build:
  stage: build
  script:
    - docker run --rm -v $(pwd):/code:ro -w /code --entrypoint=/code/ci/build.sh bluetab/amazonlinux-reactjs:latest
  artifacts:
    untracked: true
  except:
    - tags
