// Visualization types
export const IMPACT_VISUALIZATION = "impact";
export const LINEAGE_VISUALIZATION = "lineage";

// Lineage API
export const REQUEST_ELEMENTS_BY_LEVEL = "REQUEST_ELEMENTS_BY_LEVEL";
export const REQUEST_ELEMENTS_BY_LEVEL_RECEIVED =
  "REQUEST_ELEMENTS_BY_LEVEL_RECEIVED";
export const REQUEST_ELEMENTS_BY_LEVEL_FAILED =
  "REQUEST_ELEMENTS_BY_LEVEL_FAILED";
export const SET_RESOURCES_LIST = "SET_RESOURCES_LIST";
export const CLEAN_RESOURCES_LIST = "CLEAN_RESOURCES_LIST";
export const REDIRECT_TO_VISUALIZATION = "REDIRECT_TO_VISUALIZATION";
export const LINEAGE_CLEAN_STATE = "LINEAGE_CLEAN_STATE";
